theme: minima

plugins:
  - jekyll-titles-from-headings

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 

title: League of legends toplane impact analysis
author:
  name: 'Marco Sanchez'
  email: 'mas023@ucsd.edu'

description: >
  Analysis on whether having a toplaner ahead in gold 
  15 minutes into the game makes winning the game more likely.


